language: node_js
node_js:
- 0.10.36
deploy:
  provider: heroku
  api_key:
    secure: QbtD12wrg13lY7hzoN/NjqkSucTWJuRNtcSJUfpmifQONm7xte+piwHDPkq2AzBv64KSXefi74SF6/q/QVyYVgmMdHx47mC6EXJFDBPckn7yb2qeTyYpU4GrbxgZTHMKVbCF4cONrsYt+BQ7NHmnIeV+sM12oiSKcOHZN7mZEmDFKcpUt6oJpuYMkps1A2Lv+9X+L0U4J1MJA7Nb49eT5yVF9pcU/5iIpqxvhtrWBKOLBPJ4slsFCynwRJbdUGtBB/nd6lulNOrk9NOUiHSYKwNzd8d11kLBIgEbSsVCqcFiSeCNXJao1y+KhODM7HEqEHdqpdAFHV6bzJXeQIyVlyaAp83W9ccPUPp/PoHHKvm09v+WCbViWNHERVZ4e31xmTal+mTehGZ+6FawH/YzmMkxZNhBC01t1rMoexwULn5BhXDiECjyLRkjUoO/mEfr98XEUa1bO6vCk40KSJkwjG6ec0Vg51YpdTVqhvzzg9L+U/NBWMTcKzikFt/xImY/XCdGIWoX7xTizngPZehmvVQzSqKHxSX0b7YudOt/KUuFw76+nx2GMzst6HeH/COpZpM5wUzm5PBJ6fms54nSgFothBaL3uNsLVKVI6W/iSPQq7Jpy6chT80hca6qGD0T4XSm3BwyrLDJsXl+jxzZLujKfyna3H5+YuumQlVvJOs=
  app: habana
  on:
    repo: fraxedas/habana
