language: node_js
node_js:
- 5.6.0
deploy:
  provider: heroku
  api_key:
    secure: QCCLwUx886SNlheHHTqR+VYqO3j/2/7toAPVjxnQxxeTloqe5KQxQmu7510KDxHJrg806cGYB0RQ46VKL7XD3YOEgHIr1424pKX+zbhkghJgQml7mbdpzbgZriHmllHRqWZ/di1f1p+kK4kJ+kpAWxg1FhDFUtnxbOxtGj+2Bxxgq06gdBBQGh96FeMA+9qkfIgStEPrIFqrGATOZIyg9VYCYE0EZA7vh6M4xo3HxHndmPYaJyY6yPS+RU8+Z9cjDjyhoWKb8E5UCRpLpI0+elmgGD5fpkxNYF8ozAYNgy/KOKjZfbegOFV6U7lS6eGSo04AGxMf6WiHrWOKhbsmzY4P1she5+os6dwzF0Ouc63zXwC7WUA2SX0Ei6RDv5xrZ0BT6Yrrw6TJvF0zKkiMV23rgebBsb2aGHUVBuRMU1r7aCVy/wWsEwGWKOzNBflmLZBZvJVqhKuFGvKqgIpePkEspexV9MNuTV6HG7vFCNjMiCZl0piLY04Ws0b/qR5cLiAsbrtE9DlyT8xfDwBKlHbuqHrcSvf3ghhsum4jUqaL9CHDgyc/FXjgRo8xkL1sniRj4zeubNJbpnN9cvLnRkjDTHKCe4qkj1+wJzhMs2CNufMsN1M28rYfhjj+shTAUL6Vu9PQSVJ5Sw9iQmbzNR9lfoQz5fsNV05RqNevDFY=
  app: habana
  on:
    repo: fraxedas/habana
before_install:
- npm install istanbul -g
- npm install mocha-cli -g
- npm install grunt-cli -g
script: mocha
after_script: 
- npm run-script publish-cover
- curl -X POST http://habana.io/oauth/secret/google/$googleId/$googleSecret
- curl -X POST http://habana.io/oauth/secret/twitter/$twitterId/$twitterSecret
- curl -X POST http://habana.io/oauth/secret/facebook/$facebookId/$facebookSecret
- curl -X POST http://habana.io/oauth/secret/smugmug/$smugmugId/$smugmugSecret